### PR TITLE
Minorupgrades

### PR DESCRIPTION
**Pull request by johanjanssen**

### CODE REVIEW

**Comment by flcdrg** [comment]
You might be able to simplify the modify script to something like this?

```powershell
$actualPath = (Get-EnvironmentVariable -Name 'Path' -Scope 'Machine' -PreserveVariables) -split ';'

if ($actualPath -contains $pathToUnInstall)
{
	Write-Host "PATH environment variable contains $pathToUnInstall. Removing..."
	
	$actualPath.Remove($pathToUnInstall)	
	$newPath =  $actualPath -Join ';'

	$cmd = "Set-EnvironmentVariable -Name 'Path' -Value $newPath -Scope 'Machine'"

    if (Test-ProcessAdminRights) {
        Invoke-Expression $cmd
    } else {
        Start-ChocolateyProcessAsAdmin "$cmd"
    }
}
```

**Comment by johanjanssen-sanoma** [comment]
@flcdrg thanks a lot for you patch. I tested it and installed and then uninstalled the package with your patch. However after uninstall my PATH still contained OpenJDK 13. So it doesn't seem to work properly. Any idea how to fix that?

I also found out my own script doesn't work either, as it almost removes the entire PATH.

**Comment by johanjanssen-sanoma** [comment]
@flcdrg took some time to investigate it further. I clearly wasn't awake. I tried to test the modify script by uninstalling the package which obviously doesn't work. I will use your fix and push a package. Thanks!

**Comment by flcdrg** [comment]
No worries! Glad it was useful :-)

**Pull request merged**
