### PR TITLE
Migrate to portable package

### LINKED ISSUE #1: Portable OpenJDK?
Currently OpenJDK isn't portable. Interested to make it portable?

### PR DESCRIPTION
**Pull request by FranklinYu**
Closes #1.

It is expected that user having v11.0.0 or v11.0.1 installed would upgrade to this version without issue. I have tested only in one machine.

Upgrade from v11.0.1:

```powershell
choco install openjdk
choco upgrade --debug --verbose --source=. openjdk
```

From v11.0.0:

```powershell
choco install openjdk --version 11.0
choco upgrade --debug --verbose --source=. openjdk
```

Implementation note: the polyfilled function will be implemented in chocolatey/choco#1663.

### CODE REVIEW

**Comment by johanjanssen** [comment]
Thanks a lot for the commits @FranklinYu! 

I've been looking into portable packages a bit more. From what I've read portable packages have some advantages and 'normal' install packages have some other advantages. 

So my idea would be to keep the current openjdk install package as is. Then I'll create another package for the portable one. So then the portable one can be installed with choco install openjdk.portable. That way users can pick whatever installation option they want. 

What do you think about that? I could probably do that this week or next week.

**Comment by FranklinYu** [comment]
> 'normal' install packages have some other advantages.

?

**Comment by johanjanssen** [comment]
For instance being more visible installed in a more common directory instead of hidden somewhere within a Chocolatey directory. I'm more then happy to create a portable package, but I also don't want to upset people who already use the current package. So I'd rather stick to the current package and create a second portable package next to it.

**Comment by FranklinYu** [comment]
Closed by https://chocolatey.org/packages/openjdk.portable

**Pull request closed without merging**
