### PR TITLE
test

### PR DESCRIPTION
**Pull request by johanjanssen**

### CODE REVIEW

**Comment by cclauss** [comment]
When you (the owner of the repo) create a PR (like this one), Travis CI creates two separate runs (just above).
* https://travis-ci.com/johanjanssen/ChocolateyPackages/builds/111556405 on __test__ branch.
* https://travis-ci.com/johanjanssen/ChocolateyPackages/builds/111556476 on __master__ branch.
When I (an outsider) creates a PR (like #14), Travis CI creates just one run:
* https://travis-ci.com/johanjanssen/ChocolateyPackages/pull_requests

**Comment by johanjanssen** [comment]
Ah yes now I see it and I also see why I didn't get the result I expected. The Travis script you created uses the existing Chocolatey package. Which doesn't include the latest changes in the pull request as the Chocolatey package needs to be created and verified before it's actually available.

So I think it would be better to create a (local) Chocolatey package based on the code in the pull request and test if it installs successfully? See https://github.com/chocolatey/choco/wiki/CreatePackages#build-your-package for more information.

I think it would enable us to verify the changes in the pull request better. What do you think about it?

**Comment by cclauss** [comment]
Yes.  Sounds right to me to test the actual changes being made.  Also see #15.

**Comment by johanjanssen** [comment]
Ok, what I was wondering about, you set the PATH with the env variable in Travis. However, Chocolatey should already configure the PATH with Java. See for instance: https://github.com/johanjanssen/ChocolateyPackages/blob/master/AdoptOpenJDK/tools/chocolateyinstall.ps1

However, it doesn't seem to work properly with your example as the build fails because Java cannot be found. Is it possible to work around it and use the PATH as configured by my Chocolatey scripts? That would make it easier I guess.

**Comment by cclauss** [comment]
https://travis-ci.com/johanjanssen/ChocolateyPackages/jobs/199636361#L37-L39

Travis is asking the user to do one of two things:
1. Reboot your shell -- this will not work in a headless operation like Travis CI
2. Run __refreshenv__ in powershell.  [Travis has some support for powershell](https://docs.travis-ci.com/user/reference/windows/#powershell) but I am unable to figure out how to make it work.

**Pull request closed without merging**
