### PR TITLE
Try a multiline powershell

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by johanjanssen** [comment]
It seems like the PATH isn't refreshed when using refreshenv. I also tried all kinds of things today, but never saw the JDK on the PATH :(.

**Comment by johanjanssen** [comment]
Apparently: if you are installing chocolatey itself and other apps via chocolatey on the same script which modifies the PATH variable, the refreshenv won't work. The refreshenv only works on subseqent shells opened.

Source: https://stackoverflow.com/questions/17794507/reload-the-path-in-powershell

**Comment by cclauss** [comment]
IT WORKS!

**Comment by johanjanssen** [comment]
Yes, I saw it cool, great job!

However, I guess we should remove the "|| true" as it always resolves to true?

And I don't  understand where the last line is coming from: /c/Users/travis/.travis/functions: line 104: java: command not found. 

It displays the Java version info...

**Comment by johanjanssen** [comment]
I think I spotted the issue you're doing java -version twice. Once in the script and once in the yml file. Apparently one of them fails...

**Comment by cclauss** [comment]
It is an innershell (powershell), outershell (bash) thing. See the comments on the last two lines.

**Comment by johanjanssen** [comment]
Yes indeed, but then we should maybe not execute 'java -version' in the outershell? As it might confuse people who look at the Travis output. They might think something is wrong, while we now know it's the desired output.

**Comment by johanjanssen** [comment]
Almost there :). I noticed the WildFly build succeeds, however the output is as follows: java : The term 'java' is not recognized as the name of a cmdlet, function, script file, or operable program. Check 

It looks like the builds now always succeed, whether Java is present or not :(. I guess we should give the status back from the subshell or something like that?

**Comment by cclauss** [comment]
Would it be possible to add two lines to the end of __chocolateyinstall.ps1__?
```powershell
New-Item temp.sh
Set-Content temp.sh 'export PATH=C:/Program Files/AdoptOpenJDK/jdk-12+33/bin $PATH'
```
if so, we avoid the powershell subshell thing altogether and could follow up the __choco__ command with __source temp.sh__.

**Comment by johanjanssen** [comment]
I could add the two lines to the Chocolatey install files. But it adds extra configuration and it basically doesn't test the existing configuration, right? I mean a build with Travis might succeed, but the path set by Chocolatey might still be wrong.

I would prefer if we can automatically test the Chocolatey scripts, so if the download succeeds and if the path is configured correctly. That way we can hopefully prevent more mistakes.

**Comment by cclauss** [comment]
I see two problems:
1. [A failing powershell](https://travis-ci.com/johanjanssen/ChocolateyPackages/jobs/199944822#L51-L54) does not trigger a failure in the Travis job run -- I have no solution.
2. We are testing the published package, not the package that is currently being worked on.

**Comment by johanjanssen** [comment]
1. I just came across this, did you try that already? https://medium.com/@manjula.cse/how-to-stop-the-execution-of-travis-pipeline-if-script-exits-with-an-error-f0e5a43206bf 
2. Yes, that's something that needs to be improved someday :).

**Comment by johanjanssen** [comment]
I think you need to place the command in the .travis.ps1 file? Something like java -version || travis_terminate?

**Comment by cclauss** [comment]
+ java -version || travis_terminate 1
+               ~~
The token '||' is not a valid statement separator in this version.

**Comment by cclauss** [comment]
How do you to a trial run before submitting a package?  Can you do something like:
__choco install https://github.com/johanjanssen/ChocolateyPackages/tree/master/AdoptOpenJDK__

**Comment by cclauss** [comment]
https://travis-ci.community/t/getting-a-failure-in-a-powershell-job-to-fail-the-travis-ci-job/3394

**Comment by johanjanssen** [comment]
You first need to package and than install.
- Open a command line in the directory where the nuspec is and type [[choco pack|
- To test the package you just built, open a command line shell and navigate to the directory where the *.nupkg file is located. Then type: choco install packageName -dv -s .

More info:
https://github.com/chocolatey/choco/wiki/CreatePackages#build-your-package

**Comment by johanjanssen** [comment]
For the travis_terminate command. Maybe it's possible to retrieve the exit code of java -version and check it with an if statement. If it didn't execute properly call travis_terminate. See: https://stackoverflow.com/questions/24994595/checking-exit-code-of-last-command-using-if-statement

I hope to have some more time later this week. Today I'm busy with some last minute rehearsals/preparations for a conference tomorrow.

**Comment by cclauss** [comment]
It would be cool if you could go to https://travis-ci.com/johanjanssen/ChocolateyPackages/settings and turn on __Auto cancel pull request builds__.  That way if I push a second commit to a PR, Travis will kill the first tests so that the second test can run right away.

**Comment by johanjanssen** [comment]
Thanks for the tip, I just activated it.

**Comment by johanjanssen** [comment]
Thanks a lot for your help! I will try to make a check so the build fails if the java -version command fails.

**Comment by johanjanssen** [comment]
@cclauss I managed to fail the Travis build by using 'exit 1' in the Powershell script. For more info see https://github.com/johanjanssen/ChocolateyPackages/blob/master/.travis.ps1. Thanks again for all your help!

**Pull request merged**
